apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  ports:
  - port: 80
  type: NodePort
  selector:
    app: fastapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: fastapi
        ports:
        - containerPort: 80
